language: scala

sudo: required

scala: 
  - 2.10.4

before_install:
  - R CMD javareconf
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_github jimhester/robustr
  - ./travis-tool.sh install_github jimhester/covr

install:
  - ./travis-tool.sh install_deps

script: 
  - ./inst/run_test.sh

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=1
